In [1]:
import torch

In [2]:
# Creating a tensor from a list
tensor_a = torch.tensor([11.0, 23.0, 13.0])
print(tensor_a)

tensor([11., 23., 13.])


In [4]:
# Basic tensor operations
tensor_b = torch.tensor([4.0, 5.0, 6.0])
result = tensor_a + tensor_b
print(result)

tensor([15., 28., 19.])


In [5]:
# Element-wise multiplication
result = tensor_a * tensor_b
print(result)

tensor([ 44., 115.,  78.])


In [6]:
# Create a tensor with random values
tensor_random = torch.rand(3, 3)  # 3x3 tensor
print(tensor_random)

tensor([[0.9469, 0.3733, 0.2010],
        [0.1379, 0.6365, 0.2998],
        [0.4563, 0.0820, 0.2894]])


In [7]:
print(tensor_a.shape)   # Shape of the tensor
print(tensor_a.dtype)   # Data type of the tensor
print(tensor_a.device)  # Device (CPU or GPU)

torch.Size([3])
torch.float32
cpu


In [8]:
# moving tensors to GPU -> 
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_a = tensor_a.to(device)

In [9]:
tensor_a.device

device(type='cuda', index=0)

In [10]:
torch.cuda.is_available()

True

In [11]:
# tensor indexing and slicing
tensor_c = torch.tensor([10, 20, 30, 40, 50])

print(tensor_c[2:4])

tensor([30, 40])
