In [1]:
import torch

In [2]:
# create a tensor with gradient tracking
x = torch.tensor([2.0,4.0], requires_grad = True)
print(x)

tensor([2., 4.], requires_grad=True)


In [3]:
y = x * 2
print(y)

tensor([4., 8.], grad_fn=<MulBackward0>)


In [4]:
z = y.sum()
print(z)

tensor(12., grad_fn=<SumBackward0>)


In [5]:
# computing gradients
z.backward()   # compute dz/dx
print(x.grad)  # gradient of z with respect to x

tensor([2., 2.])


In [6]:
# disabling gradient tracking
with torch.no_grad():
    y = x * 3
    print(y) 

tensor([ 6., 12.])


In [7]:
# clearing gradients
x.grad.zero_()

tensor([0., 0.])

In [8]:
from torchviz import make_dot

# Visualize the graph
make_dot(z, params={"x": x}).render("graph", format="png")

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH